import Head from 'next/head'
import { fetchContent } from '../utils/contentful'
import Image from "next/image"

import Post from '../components/Post'

export default function Home({ posts }) {
  const firstPost = posts[0];
  return (
    <div>
      <Head>
        <title>Bloggerfy</title>
        <meta name="NextJS Blog with Contentful" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Post 
        title={firstPost.title}
        date={firstPost.publishDate}
        image={firstPost.heroImage.url}
        alt={firstPost.title}
        author={firstPost.author.name}
        tags={firstPost.tags}
        body={firstPost.body.json}
      />
      
      <footer>

      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const response = await fetchContent(`
    query myQuery {
      blogPostCollection (order: publishDate_DESC) {
        items {
          title
          slug
          heroImage {
            url
          }
          publishDate
          author {
            name
          }
          body {
            json
          }
          tags
        }
      }
    }
  `);
  return {
    props: {
      posts: response.blogPostCollection.items,
    }
  }
}